
FROM node:24-alpine


WORKDIR /app

COPY package*.json ./

# Install project dependencies.

RUN npm install

# Copy the rest of the application code to the container.
COPY . .

# Expose the port the app runs on.
# This is for documentation purposes; it doesn’t actually publish the port.
EXPOSE 4000

# Define the command to run the app.
CMD ["npm", "run", "dev"]